# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    git_pull(only_tags: true)
    setup_circle_ci
  end
  
  desc "deploy new build for beta crashlytics project"
  lane :beta do
    increment_build_number
    match(type: "enterprise")
    gym(
      scheme: "FastlaneSample",
      export_method: "enterprise",
      xcargs: "ARCHIVE=YES")
    crashlytics(
      api_token: "170c87df1b26132ef28510f40376dd75cb61f489",
      build_secret: "993c5ab5dbbd48e1f585a02fe66762340c4f8860b2136e177d9a9c6c341de21c",
      groups: "fastlane-tester",
      notes: change_log_since_last_tag
    )
  end
  
  def setup_circle_ci
    # ENV["MATCH_PASSWORD"]="abc123"
    # ENV["FASTLANE_PASSWORD"]="Starfall0216"
  end
  
  def change_log_since_last_tag
    return changelog_from_git_commits(pretty: '%h %s')
  end
end
